---
# PyCatDetector Basics
log_tty: false
log_dir: "./logs"
log_level: "info"
rtsp_url: "rtsp://username:password@192.168.1.2:554/stream1"
headless: true
# https://cv.gluon.ai/model_zoo/detection.html
# net_model_name: 'ssd_512_resnet50_v1_voc'  # PC (Slower), min_score = 0.9
net_model_name: 'ssd_512_mobilenet1.0_voc'  # IoT (Faster), min_score = 0.9
net_min_score: 0.9

# PyCatDetector Notifiers
notifiers:
  ha_google_say:
    enabled: true
    url: "http://homeassistant.local:8123/api"
    token: "token123ABC"
    entity: "media_player.nesti"
    message: "El gato está en la caja de arena."
    language: "es"
    objects:
      - "cat"
  discord_webhook:
    enabled: true
    url: "https://discordapp.com/api/webhooks/X/Y"
    content: "Hay una planta cerca de la caja de arena."
    objects:
      - "pottedplant"
