---
version: "3"
services:
  pycatdetector:
    build: .
    image: olafrv/pycatdetector:latest
    container_name: pycatdetector
    volumes:
    - ./config.yaml:/opt/pycatdetector/config.yaml:ro
    - ./logs:/opt/pycatdetector/logs:rw

# networks:
#  default:
#    name: containers
#    external: true