services:
  pycatdetector:
    build: .
    image: ghcr.io/olafrv/pycatdetector:latest
    container_name: pycatdetector
    environment:
      - TZ=Europe/Berlin
    volumes:
    - ./config.yaml:/opt/pycatdetector/config.yaml:ro
    - ./logs:/opt/pycatdetector/logs:rw
    - ./videos:/opt/pycatdetector/videos:rw
    restart: always
    deploy:
        resources:
            limits:
              memory: 640M
            reservations:
              memory: 512M

# networks:
#  default:
#    name: containers
#    external: true
