services:
  pycatdetector:
    build: .
    image: ghcr.io/olafrv/pycatdetector:latest
    container_name: pycatdetector
    environment:
      - TZ=Europe/Berlin
      # Used for debugging OpenCV issues with versions upgrade
      # Uncomment the following lines to enable detailed OpenCV logging
      # See also Recorder.py for more OpenCV debugging options
      # https://github.com/opencv/opencv/issues/27091 (Bug)
      - OPENCV_LOG_LEVEL=DEBUG
      - OPENCV_VIDEOIO_DEBUG=1
    volumes:
    - ./config.yaml:/opt/pycatdetector/config.yaml:ro
    - ./logs:/opt/pycatdetector/logs:rw
    - ./videos:/opt/pycatdetector/videos:rw
    - ./models:/root/.cache/torch:rw
    restart: always
    deploy:
        resources:
            limits:
              memory: 1024M
            reservations:
              memory: 512M

# networks:
#  default:
#    name: containers
#    external: true
