---
version: "3"
services:
  pycatdetector:
    build: .
    image: olafrv/pycatdetector:latest
    container_name: pycatdetector
    volumes:
    - ./config.json:/opt/pycatdetector/config.json
    - ./logs:/opt/pycatdetector/logs

# networks:
#  default:
#    name: containers
#    external: true